export const RESERVATION_LABEL = {
  optionHeader: "옵션",
  reset: "초기화",
  keywordPlaceholder: "여기에 검색어",
  discardedTitle: "취소된 연습실 예약 관리",
  discardedReservationId: "예약 ID",
  discardedByType: "처리 주체",
  discardedReason: "사유",
  discardedCreatorClub: "예약자 / 동아리",
  discardedCreatedAt: "취소 시각",
  loading: "불러오는 중...",
  noAffiliation: "/ 소속 없음",
  noValue: "—",
  practiceTitle: "연습 제목",
  regularPractice: "정규 연습",
  openPractice: "열린 연습",
  yes: "예",
  no: "아니오",
} as const;
