import type { Metadata } from "next";
import "@admin/app/globals.css";


export const metadata: Metadata = {
  title: "Login HongPung",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="ml-16 w-full flex flex-col items-center">
      {children}
    </div>
  );
}
