import type { Metadata } from "next";
import "@admin/app/globals.css";
import { geistMono, geistSans } from "@fonts";


export const metadata: Metadata = {
  title: "Login HongPung",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {children}
    </div>
  );
}
