export const ADMIN_MANAGE_TEXT = {
  levelLabel: {
    super: "의장",
    sub: "패짱",
    empty: "—",
  },
  levelDisplay: {
    super: "의장 (SUPER)",
    sub: "패짱 (SUB)",
    empty: "—",
  },
  pageTitle: "관리자 계정",
  sessionGuidePrefix: "세션",
  sessionGuideSuffix: "(JWT에 memberId·adminLevel이 있으면 버튼 표시가 정확해집니다.)",
  subAdminReadonly:
    "패짱은 목록만 조회할 수 있습니다. 권한 부여·변경·제거는 의장만 가능합니다.",
  grantGuidePrefix: "우하단",
  grantGuidePlus: "+",
  grantGuideSuffix: "로 회원을 검색·선택해 관리자를 추가할 수 있습니다.",
  columnTitleName: "이름 (패명)",
  columnTitleClub: "동아리 (학번)",
  columnTitleAdminLevel: "관리자 등급",
  rowNoClub: "무소속",
  rowSelf: "본인",
  rowManageAction: "관리",
  tableEmptyText: "등록된 관리자가 없습니다.",
  modalManageTitle: "관리자 권한",
  modalSelectedAdmin: "선택된 관리자",
  modalCurrentLevel: "기존 등급",
  modalNextLevel: "변경할 등급",
  modalRevokeAction: "관리자 권한 제거",
  modalChangeAction: "변경",
  grantModalTitle: "관리자 지정",
  grantModalSearchLabel: "회원 검색",
  grantModalReset: "초기화",
  grantModalSearchPlaceholder: "여기에 검색어",
  grantModalClubFilter: "동아리",
  grantModalRoleFilter: "역할",
  grantModalAlreadyAdmin: "이미 관리자",
  grantModalSelectedUser: "선택된 유저",
  grantModalMemberId: "회원 ID",
  grantModalClubAndEnrollment: "동아리 (학번)",
  grantModalTargetLevel: "부여할 관리자 등급",
  grantModalCancelSelection: "선택 취소",
  grantModalRegister: "등록",
  grantModalLoading: "로딩중...",
  grantModalEmptyResult: "검색 결과 없습니다.",
  grantColumnTitleName: "이름 (패명 · 학번)",
  grantColumnTitleClub: "동아리",
  grantColumnTitleRole: "역할",
} as const;

export const ADMIN_MANAGE_CLUB_OPTIONS = [
  { value: "none", label: "동아리" },
  { value: "0", label: "들녘" },
  { value: "1", label: "산틀" },
  { value: "2", label: "악반" },
  { value: "3", label: "신명화랑" },
] as const;

export const ADMIN_MANAGE_ROLE_OPTIONS = [
  { value: "none", label: "역할" },
  { value: "패짱", label: "패짱" },
  { value: "상쇠", label: "상쇠" },
  { value: "상장구", label: "상장구" },
  { value: "수북", label: "수북" },
  { value: "수법고", label: "수법고" },
] as const;
